# Generated by Django 4.0.1 on 2022-01-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0007_rename_note_correct_note_erronee_note_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.CharField(max_length=20),
        ),
    ]
