# Generated by Django 4.0.1 on 2022-01-19 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Admin', models.CharField(max_length=30, unique=True)),
                ('departement', models.CharField(max_length=30)),
                ('grade', models.CharField(choices=[('Chargé de cours', 'Chargé de cours'), ('Enseignant', 'Enseignant'), ('Doctorant', 'Doctorant'), ('Doyen', 'Doyen'), ('Vice_Doyen', 'Vice_Doyen'), ('Recteur', 'Recteur')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=8, unique=True)),
                ('filiere', models.CharField(max_length=20)),
                ('niveau', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(max_length=30, null=True)),
                ('theme', models.CharField(max_length=30, null=True)),
                ('couleur_avartar', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateHeureRep', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requete_personalisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('Administration', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APPLICATION.administration')),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APPLICATION.etudiant')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APPLICATION.reponse')),
            ],
        ),
        migrations.CreateModel(
            name='ReqInformation_eronee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('ancienneInfo', models.CharField(max_length=50)),
                ('nouvelleInfo', models.CharField(max_length=50)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APPLICATION.administration')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APPLICATION.etudiant')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APPLICATION.reponse')),
            ],
        ),
        migrations.CreateModel(
            name='ReqDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('nomDocument', models.CharField(max_length=20)),
                ('anneeAcademique', models.CharField(max_length=10)),
                ('Administration', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APPLICATION.administration')),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APPLICATION.etudiant')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APPLICATION.reponse')),
            ],
        ),
        migrations.CreateModel(
            name='ReqAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('unite_enseignement', models.CharField(max_length=30)),
                ('examen', models.CharField(max_length=30)),
                ('Administration', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APPLICATION.administration')),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APPLICATION.etudiant')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APPLICATION.reponse')),
            ],
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pieceJointe', models.CharField(max_length=50)),
                ('type_pieceJointe', models.CharField(max_length=10)),
                ('pieceJointe', models.FileField(upload_to='Pieces')),
                ('req_abs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.reqabsence')),
                ('req_dem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APPLICATION.reqdemande')),
                ('req_inf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.reqinformation_eronee')),
                ('req_perso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.requete_personalisee')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='preference',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.preference'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administration',
            name='preference',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.preference'),
        ),
        migrations.AddField(
            model_name='administration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
