# Generated by Django 4.0.1 on 2022-01-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requete',
            name='id_request',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
 