# Generated by Django 4.0.1 on 2022-01-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administration',
            name='id_Admin',
        ),
    ]
