# Generated by Django 4.0.1 on 2022-01-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reqabsence',
            old_name='Administration',
            new_name='administration',
        ),
        migrations.RenameField(
            model_name='reqabsence',
            old_name='Etudiant',
            new_name='etudiant',
        ),
        migrations.RenameField(
            model_name='reqdemande',
            old_name='Administration',
            new_name='administration',
        ),
        migrations.RenameField(
            model_name='reqdemande',
            old_name='Etudiant',
            new_name='etudiant',
        ),
        migrations.RenameField(
            model_name='requete_personalisee',
            old_name='Administration',
            new_name='administration',
        ),
        migrations.RenameField(
            model_name='requete_personalisee',
            old_name='Etudiant',
            new_name='etudiant',
        ),
    ]
