# Generated by Django 4.0.1 on 2022-01-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0002_remove_note_erronee_requete_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abscence_payement',
            name='requete_ptr',
        ),
        migrations.RemoveField(
            model_name='activation_de_matricule',
            name='requete_ptr',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='bloquage_matricule',
            name='requete_ptr',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='requete_ptr',
        ),
        migrations.RemoveField(
            model_name='envoyer',
            name='administration',
        ),
        migrations.RemoveField(
            model_name='envoyer',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='envoyer',
            name='requete',
        ),
        migrations.RemoveField(
            model_name='information_eronee',
            name='requete_ptr',
        ),
        migrations.RemoveField(
            model_name='piecejointe',
            name='requete',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='requete',
        ),
        migrations.DeleteModel(
            name='Abscence_note',
        ),
        migrations.DeleteModel(
            name='Abscence_payement',
        ),
        migrations.DeleteModel(
            name='Activation_de_matricule',
        ),
        migrations.DeleteModel(
            name='Administration',
        ),
        migrations.DeleteModel(
            name='Bloquage_matricule',
        ),
        migrations.DeleteModel(
            name='Demande',
        ),
        migrations.DeleteModel(
            name='Envoyer',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Information_eronee',
        ),
        migrations.DeleteModel(
            name='PieceJointe',
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
        migrations.DeleteModel(
            name='Requete',
        ),
    ]
