# Generated by Django 4.0.1 on 2022-01-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0002_alter_requete_id_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='id',
        ),
        migrations.AddField(
            model_name='reponse',
            name='id_request',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
