# Generated by Django 4.0.1 on 2022-01-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0002_rename_administration_reqabsence_administration_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requete_personalisee',
            new_name='ReqPersonalise',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='id_Admin',
        ),
    ]
