# Generated by Django 4.0.1 on 2022-01-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0002_remove_administration_id_admin'),
        ('APPLICATION', '0003_rename_requete_personalisee_reqpersonalise_and_more'),
    ]

    operations = [
    ]
