# Generated by Django 4.0.1 on 2022-01-16 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APPLICATION', '0003_remove_abscence_payement_requete_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Admin', models.CharField(max_length=30, unique=True)),
                ('departement', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=8, unique=True)),
                ('filiere', models.CharField(max_length=20)),
                ('niveau', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_grade', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_request', models.CharField(max_length=10, unique=True)),
                ('objet', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReqAbscence',
            fields=[
                ('requete_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='APPLICATION.requete')),
                ('unite_enseignement', models.CharField(max_length=30)),
                ('examen', models.CharField(max_length=30)),
            ],
            bases=('APPLICATION.requete',),
        ),
        migrations.CreateModel(
            name='ReqDemande',
            fields=[
                ('requete_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='APPLICATION.requete')),
                ('nomDocument', models.CharField(max_length=20)),
                ('anneeAcademique', models.CharField(max_length=10)),
            ],
            bases=('APPLICATION.requete',),
        ),
        migrations.CreateModel(
            name='ReqInformation_eronee',
            fields=[
                ('requete_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='APPLICATION.requete')),
                ('info_erronee', models.CharField(max_length=100)),
                ('ancienneInfo', models.CharField(max_length=50)),
                ('nouvelleInfo', models.CharField(max_length=50)),
            ],
            bases=('APPLICATION.requete',),
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reponse', models.CharField(max_length=20, unique=True)),
                ('dateHeureRep', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=15)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.administration')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.etudiant')),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.requete')),
            ],
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pieceJointe', models.CharField(max_length=50)),
                ('type_pieceJointe', models.CharField(max_length=10)),
                ('pieceJointe', models.FileField(upload_to='Pieces')),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.requete')),
            ],
        ),
        migrations.CreateModel(
            name='Envoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_envoi', models.CharField(max_length=20, null=True, unique=True)),
                ('dateHeureEnvoie', models.DateTimeField()),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.administration')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.etudiant')),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.requete')),
            ],
        ),
        migrations.AddField(
            model_name='administration',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.grade'),
        ),
        migrations.AddField(
            model_name='administration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
