# Generated by Django 4.0.1 on 2022-01-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0003_remove_reponse_id_reponse_id_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponse',
            old_name='id_request',
            new_name='id_reponse',
        ),
    ]
