# Generated by Django 4.0.1 on 2022-01-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0004_rename_id_request_reponse_id_reponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='id_reponse',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requete',
            name='id_request',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
