# Generated by Django 4.0.1 on 2022-01-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReqAbscence',
            new_name='ReqAbsence',
        ),
        migrations.AlterField(
            model_name='reponse',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='requete',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
