# Generated by Django 4.0.1 on 2022-01-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0005_alter_reponse_id_reponse_alter_requete_id_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='note_erronee',
            name='Note_correct',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
