# Generated by Django 4.0.1 on 2022-01-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0005_rename_reqabscence_reqabsence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(max_length=30, null=True)),
                ('theme', models.CharField(max_length=30, null=True)),
                ('couleur', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reqinformation_eronee',
            name='info_erronee',
        ),
    ]
