# Generated by Django 4.0.1 on 2022-01-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0006_preference_remove_reqinformation_eronee_info_erronee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='couleur',
            new_name='couleur_avartar',
        ),
    ]
