# Generated by Django 4.0.1 on 2022-01-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0006_note_erronee_note_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note_erronee',
            old_name='Note_correct',
            new_name='note_correct',
        ),
        migrations.RenameField(
            model_name='note_erronee',
            old_name='Note_erronee',
            new_name='note_errone',
        ),
    ]
