# Generated by Django 4.0.1 on 2022-01-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0007_rename_couleur_preference_couleur_avartar'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='preference',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.preference'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='preference',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.preference'),
        ),
    ]
