# Generated by Django 3.2 on 2022-01-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0008_administration_preference_etudiant_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='couleur_avartar',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
