# Generated by Django 3.2 on 2022-01-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0010_alter_preference_couleur_avartar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administration',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='preference',
        ),
    ]
